const excursiones = [{
    id: 1,
    foto: "https://static.nationalgeographic.es/files/styles/image_3200/public/reflection-salar-de-uyuni-bolivia.webp?w=900&h=507",
    nombre: "Laguna Cejar + Ojos del Salar",
    precio: 230,
},
{
    id: 2,
    foto: "https://sajamaexpediciones.com/data/atacama/fa14d2589b0aaa6adac627ace36403b5.jpeg",
    nombre: "Piedras Rojas + Lagunas",
    precio: 100,
},
{
    id: 3,
    foto: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/bc/57/a7/valle-arcoiris.jpg?w=1200&h=-1&s=1",
    nombre: "Valle Arcoiris",
    precio: 50,
},
{
    id: 4,
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4HiYrGnVCKUGPEerWivRm96W-mXRaoMavIlXHAVGfyA&s",
    nombre: "Baltinache",
    precio: 50,
},
{
    id: 5,
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXAPPodmP7YIZYQK7BhWiCBodz6mbkk4BOK1iTYoL7zQBBsHqW8nvPFGi4mqU9YgX5PYQ&usqp=CAU",
    nombre: "Geiser del Tatio",
    precio: 100,
},
{
    id: 6,
    foto: "https://denomades.imgix.net/destinos/san-pedro-de-atacama/132/salar-de-tara-id132-2-es.jpg",
    nombre: "Ruta de los Salares",
    precio: 60,
},
{
    id: 7,
    foto: "https://www.tangol.com/Fotos/Tours/termas-de-puritama_1549_201807060659411.JPG",
    nombre: "Termas de Puritama - AM",
    precio: 75,
},
{
    id: 8,
    foto: "https://d2g6vh54b4p2bp.cloudfront.net/wp-content/uploads/2022/04/puritama-Politicas-cambios.jpg",
    nombre: "Termas de Puritama - PM",
    precio: 75,
},
{
    id: 9,
    foto: "https://i1.wp.com/gouyuni.com/wp-content/uploads/2021/09/IMG_9271-scaled.jpg?fit=2048%2C2560&ssl=1",
    nombre: "Termas de Puripobre",
    precio: 55,
},
{
    id: 10,
    foto: "https://denomades.imgix.net/destinos/san-pedro-de-atacama/1130/vallecito.jpg",
    nombre: "Vallecito",
    precio: 45,
},
{
    id: 11,
    foto: "https://www.porquemegustaviajar.com/wp-content/uploads/2021/06/Cascada-Escondida-San-Pedro-de-Atacama.jpeg",
    nombre: "Cascada Escondida",
    precio: 50,
},
{
    id: 12,
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJbBwamZS0tKLQAR2tqGPKWn87E7jwTPqH30N-vaeZ3FzL-jsDhgv6yLe0feOY7fyeY6s&usqp=CAU",
    nombre: "Tour Astronomico",
    precio: 30,
},
]